#! /usr/bin/env php

<?php


use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

require 'vendor/autoload.php';

$app = new Application('achilles', '1.0');
$app->register('scan')
    ->setDescription('Scan target for HTTPS mixed content')
    ->addArgument('URI', InputArgument::REQUIRED, 'Target URI to Scan')
    ->setCode(function(InputInterface $input, OutputInterface $output)
    {
        // call method on target and return URLs.
    });

$app->run();
?>

