#! /usr/bin/env php

<?php

use Heel\CheckSSL;
use Heel\CheckCiphers;
use Heel\Screenshot;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('achilles', '1.0');

$app->add(new CheckSSL);
$app->add(new CheckCiphers);
$app->add(new Screenshot);

$app->run();

?>
